# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: ollama:granite3.3:latest
# model: ollama:gemma3:latest
# model: ollama:gemma3n:e2b
clients:
  - type: openai-compatible
    name: ollama
    api_base: http://localhost:11434/v1
    api_key: xxx
    models:
      # LLMs
      - name: granite3.3:latest
      - name: gemma3:latest
      - name: gemma3n:e2b
      # Embedders
      - name: nextfire/paraphrase-multilingual-minilm:l12-v2
        type: embedding
        default_chunk_size: 1000
        max_batch_size: 100
      - name: nomic-embed-text:latest
        type: embedding
        default_chunk_size: 1000
        max_batch_size: 100
